### ISSUE TITLE
为啥出会现长长的变量名 ?

### ISSUE THREAD

**Issue by biezhi** [unbug/codelf#1]
![_20151217153216](https://cloud.githubusercontent.com/assets/3849072/11863967/ae7efb4a-a4d3-11e5-82bc-b99e02f634ee.png)

**Comment by unbug** [comment]
这是个问题，因为里面有个of,那些长长长长长长长变量名给匹配上了，还没找到办法过虑掉，你就看对你有用的，有什么好办法欢迎贡献

**Comment by biezhi** [comment]
原来如此,我不知道是如何实现的,简单的可以处理一下长度,一般不会有很长的项目名称的 ; )

**Comment by unbug** [comment]
有个好主意 ：）

**Comment by unbug** [comment]
对了，上面的suggestion里你可以直接点击意思较对的单词进行查询

**Comment by unbug** [comment]
![image](https://cloud.githubusercontent.com/assets/799578/11876569/6853b35c-a525-11e5-872e-59122c4f23ee.png)

找到原因了，那些是Base64中匹配出来的结果，已经干掉了 :)
