### ISSUE TITLE
建议可以给分组加个标记

### ISSUE THREAD

**Issue by woodghost** [unbug/codelf#10]
收藏癖和强迫症患者的福音，collection多的时候就能更方便的发现是否对该项目分过组了。
<img width="171" alt="screen shot 2016-01-21 at 6 34 21 pm" src="https://cloud.githubusercontent.com/assets/12583171/12478043/c7b4be28-c06d-11e5-9ef7-a0c2bd875977.png">
在分组前面加个记号或者在
<img width="171" alt="screen shot 2016-01-21 at 6 34 21 pm" src="https://cloud.githubusercontent.com/assets/12583171/12478069/ed69679a-c06d-11e5-9319-ceae0b42518d.png">横栏这里加个组名的tag

(*^__^*) 阿里嘎多

**Comment by unbug** [comment]
这块是需要优化 ;)
