### ISSUE TITLE
指定搜索语言

### ISSUE THREAD

**Issue by ttttttssssss** [unbug/codelf#104]
在 vscode 中能设定默认的语言 例如"java" 不希望每次进入页面还要调整一下

**Comment by SKTT1Ryze** [comment]
借个楼，建议增加 `Rust` 语言选项。

**Comment by unbug** [comment]
@SKTT1Ryze 选择所有语言是可搜到 Rust 的，你重新提一个 issue，我改天加一下到列表里选择
