### ISSUE TITLE
这并不支持中文搜索.....错误的

### ISSUE THREAD

**Issue by pengpengker** [unbug/codelf#110]
![image](https://user-images.githubusercontent.com/50614901/116213641-8c7f5000-a778-11eb-8ec2-a53629bac3a6.png)
无法获取数据

**Comment by unbug** [comment]
刷新一下再试试
![535EBEC2-2338-43EC-A8FC-2800246C0F27](https://user-images.githubusercontent.com/799578/116541977-aeb2d280-a91e-11eb-944c-448b3460f727.png)

**Comment by ljm5210** [comment]
同样的搜索不了
![Uploading 微信截图_20210608233652.png…]()

**Comment by luckysunle** [comment]
> 同样的搜索不了

重新启动试试，我第一次也不能搜索中文，重启一下就ok了

**Comment by GuiSud** [comment]
还是没法搜索中文，什么问题。。。

**Comment by klierbyck** [comment]
看结果好像是有道翻译报错导致

**Comment by 7-happy** [comment]
api访问权限到期了应该
https://api.cognitive.microsofttranslator.com/translate?api-version=3.0&to=en

**Comment by 7-happy** [comment]
现在好了，中文可以正常翻译了，感谢作者~

**Comment by izkizk8** [comment]
> 又不行了~

所以应该咋解决呀

**Comment by 7-happy** [comment]
找作者喽发自我的手机-------- 原始邮件 --------发件人： izkizk8 ***@***.***>日期： 2022年5月19日周四 下午4:14收件人： unbug/codelf ***@***.***>抄送： 7-happy ***@***.***>, Comment ***@***.***>主    题： Re: [unbug/codelf] 这并不支持中文搜索.....错误的 (#110)



又不行了~



所以应该咋解决呀

**Comment by izkizk8** [comment]
> 找作者喽发自我的手机-------- 原始邮件 --------发件人： izkizk8 ***@***.***>日期： 2022年5月19日周四 下午4:14收件人： unbug/codelf ***@***.***>抄送： 7-happy ***@***.***>, Comment ***@***.***>主 题： Re: [unbug/codelf] 这并不支持中文搜索.....错误的 (#110) 又不行了~ 所以应该咋解决呀 —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

soga
