### ISSUE TITLE
中文搜索无结果

### ISSUE THREAD

**Issue by Dave1991** [unbug/codelf#112]

**Comment by klierbyck** [comment]
同样问题，一直转转转

**Comment by unbug** [comment]
多刷新几次

**Comment by YogiLai** [comment]
骗钱玩意，一直显示交不起房租

**Comment by 7-happy** [comment]
抓页面请求看是作者用的一个微软翻译的api无法访问报403了，可能是访问令牌啥的过期了
https://api.cognitive.microsofttranslator.com/translate?api-version=3.0&to=en
导致中文无法被正常翻译，输入英文是正常的能出来结果

**Comment by breathless1992** [comment]
我也是这个问题，中文搜索不出来

**Comment by breathless1992** [comment]
这用的翻译api还是收费的吗

**Comment by unbug** [comment]
可以了，已经更新翻译服务及算法
