### ISSUE TITLE
中文不能搜索

### ISSUE THREAD

**Issue by breathless1992** [unbug/codelf#113]
为啥中文搜索，要么就是一直转圈，要么就是搜索不出来呀

**Comment by unbug** [comment]
@breathless1992 被强了，多刷几次

**Comment by liu-xinhui** [comment]
英文都可以，中文无论啥关键字，试多少次都没结果

**Comment by nemowong33** [comment]
输入英文可以正常使用，中文则会提示无结果。即使翻墙也不行。

**Comment by CodeShihong** [comment]
一点用都没有，作者都不更新了？？

**Comment by srxh-max** [comment]
中文不可以搜索

**Comment by unbug** [comment]
你们搜索的啥？

**Comment by NeverMorewd** [comment]
科学上网 也不行、

**Comment by forsaken628** [comment]
api.cognitive.microsofttranslator.com 
The operation is not allowed because the subscription has exceeded its free quota.

貌似是微软翻译超量了

**Comment by unbug** [comment]
可以了，已经更新翻译服务及算法
