### ISSUE TITLE
应该 BUG 了？？？

### ISSUE THREAD

**Issue by wottery** [unbug/codelf#116]

**Comment by jyxjjj** [comment]
看请求是请求了有道翻译然后被有道ban了key

**Comment by hotstar-xia** [comment]
有没有什么替代品呀

**Comment by Strong-bb** [comment]
看了代码 注释有说 应该是超过免费的限制了  作者可能也没想到这么火吧 哈哈

  特别重要，必读！
  CODELF 用的是 Baidu 翻译 API 的免费套餐，一个月仅有200万字符请求限制！
  所以，如果你想二次开发，请单独申请自己的 Baidu 翻译 API 的 KEY，否则会直接影响 CODELF 的用户。

**Comment by Strong-bb** [comment]
看了代码 注释有说 应该是超过免费的限制了  作者可能也没想到这么火吧 哈哈

  特别重要，必读！
  CODELF 用的是 Baidu 翻译 API 的免费套餐，一个月仅有200万字符请求限制！
  所以，如果你想二次开发，请单独申请自己的 Baidu 翻译 API 的 KEY，否则会直接影响 CODELF 的用户。

**Comment by izkizk8** [comment]
@unbug 好像又没用了，还有我想问问为啥叫codelf

**Comment by unbug** [comment]
> @unbug 好像又没用了，还有我想问问为啥叫codelf

遇到服务问题，多刷新几次。CODELF = CODE + ELF，即代码精灵

**Comment by unbug** [comment]
各个服务坏了，在加班搞了

**Comment by unbug** [comment]
可以了，已经更新翻译服务及算法
