### ISSUE TITLE
😭服务不可用，加班中。。。

### ISSUE THREAD

**Issue by unbug** [unbug/codelf#124]
搜索服务维护中....
1. search code api
2. 翻译 api

**Comment by unbug** [comment]
有道的翻译 API 需要更换了

**Comment by unbug** [comment]
可以新增百度的翻译 API 作为容灾 http://api.fanyi.baidu.com/api/trans/product/prodinfo

**Comment by shuax** [comment]
期待修复

**Comment by byttao** [comment]
您好~我js很差-。- 能麻烦直接添加个inputbox，让我们自己填写有道的API的key麽？

**Comment by unbug** [comment]
可以了，已经更新翻译服务及算法
