### ISSUE TITLE
[proposal] show short summary when hover on matched results

### ISSUE THREAD

**Issue by wonderbeyond** [unbug/codelf#15]
![image](https://cloud.githubusercontent.com/assets/228361/13043139/4599d7e6-d401-11e5-9f39-e11ae2983f96.png)

For example, when I search for [RegexField](https://github.com/django/django/blob/master/django/forms/fields.py#L499), If I find a result from [Django](https://github.com/django/django) project and the file path is [django/forms/fields.py](https://github.com/django/django/blob/master/django/forms/fields.py), then I'll know it's just the official implementation, otherwise it maybe a use case of `RegexField`

I think it'll be a useful feature.

Thank you!

**Comment by unbug** [comment]
这里主要是查看不同语言的代码，我考虑一下鼠标移上去然后显示更多信息 ;)

**Comment by wonderbeyond** [comment]
Perfect!

**Comment by unbug** [comment]
项目名称，文件路径，repo连接hover效果已经添加,暂时没有获取不到项目描述休息 :)

**Comment by wonderbeyond** [comment]
感激不尽！你正在为人类创造伟大的工具。
