### ISSUE TITLE
[proposal] Provide some method for navigating to matched locations easilly

### ISSUE THREAD

**Issue by wonderbeyond** [unbug/codelf#16]
![image](https://cloud.githubusercontent.com/assets/228361/13043428/05d6bf8c-d403-11e5-8b9f-d8f4bd4ebe6b.png)

- Auto scroll to matched location?
- Mark matched locations in a minimap?
- Press `F3` for jumping to matched location?

Thanks!

**Comment by unbug** [comment]
这里比较困难，主要是Google的代码查看插件并不支持，其实目前用浏览器的搜索是可以的，我在这里可以提供一个搜索 :)

**Comment by wonderbeyond** [comment]
Your method seems OK.

Thank you!

**Comment by unbug** [comment]
现在已经有关键字高亮了 ;)
![image](https://cloud.githubusercontent.com/assets/799578/13078126/2533e378-d4f8-11e5-97e6-37b6394ba43c.png)

**Comment by unbug** [comment]
现在代码里已经直接高亮关键字了，并且`tab`键下一个`shift+tab`上一个 :)
![image](https://cloud.githubusercontent.com/assets/799578/13078382/8563eb7a-d4f9-11e5-9c40-a6e505962c7f.png)

**Comment by wonderbeyond** [comment]
Perfect! You have done what I want!

**Comment by movedata** [comment]
果然神器，治愈了我的命名纠结症！谢谢！
