### ISSUE TITLE
建议添加功能---加github Star的管理功能做成云端同步

### ISSUE THREAD

**Issue by wwcom227** [unbug/codelf#18]
发现codelf可以管理github star,这个是很方便的。而且跟其他的管理工具比较速度、体验也好很多。但可惜只能将分好的组在当前设备上持久化，建议做成可以跨设备同步的。

**Comment by unbug** [comment]
暂时在自己常用的开发机上的常用浏览器用，数据是持久化到IndexDB数据库里的，今后上线云端同步会直接同步本地的,数据不会丢失 ;)

**Comment by wwcom227** [comment]
目前我可以拷贝浏览器下面的哪个文件来通过导入进行数据同步吗？

**Comment by unbug** [comment]
IndexDB不能这么操作，你可以用JS转成JSON然后保存，具体可以看[它的表设计](https://github.com/unbug/codelf/blob/gh-pages/static/app/src/model/BookmarkModel.js)

**Comment by q351941406** [comment]
一定要做成云同步的，如今的互联网没有云同步怎么可能还有人用！！！强烈建议

**Comment by unbug** [comment]
![image](https://cloud.githubusercontent.com/assets/799578/14140479/b364a2de-f6ab-11e5-83a9-ad2e96554c21.png)

如你们所愿 ;)

**Comment by huangmingchuan** [comment]
@unbug 
你好，这个 sync id 是怎样获取呢？

**Comment by unbug** [comment]
@huangmingchuan 点击upload先上传就有了

**Comment by laris** [comment]
能不能考虑和github的private gist链接起来？
吧gist作为云上的同步数据？再增加一个时间戳来管理同步？

**Comment by unbug** [comment]
你可以提个issue.
