### ISSUE TITLE
添加 Star 备注功能

### ISSUE THREAD

**Issue by q351941406** [unbug/codelf#20]
能不能加个功能，能给某个star添加备注的功能，有太多start了，都不知道哪个是干嘛用的了，要点开看，看也看不懂，都是英文介绍。
亲，不难吧，像你这样的大牛，分分钟的事啦。我帮你拉了不少用户呀，身边不下十人天天都在用

**Comment by unbug** [comment]
我给你记上了 ;)

**Comment by q351941406** [comment]
谢谢
