### ISSUE TITLE
【教程】给 WebStorm 添加 Codelf 实现一键搜索

### ISSUE THREAD

**Issue by unbug** [unbug/codelf#24]
# Why?

这里有[Sublime Text插件](https://github.com/unbug/codelf#codelf-for-sbulime-text), [Atom 插件](https://atom.io/packages/codelf), [Alfred插件](https://github.com/unbug/codelf/issues/63), [Codelf Chrome App](https://chrome.google.com/webstore/detail/codelf-best-github-stars/jnmjaglhmmcplekpfnblniiammmdpaan)，自己用的编辑器没有 Codelf 插件也请[参考 WiKi](https://github.com/unbug/codelf/wiki#%E8%87%AA%E5%B7%B1%E7%94%A8%E7%9A%84%E7%BC%96%E8%BE%91%E5%99%A8%E6%B2%A1%E6%9C%89codelf%E6%8F%92%E4%BB%B6%E8%AF%B7%E7%9C%8B%E5%8F%82%E8%80%83%E4%BB%A5%E4%B8%8B%E6%96%B9%E6%A1%88) 。但如果你用 WebStorm，以下方法灰常方便。
# Result?

效果就是在编辑代码时选中任意文本：
- 1. 按”CTRL＋S"
- 2. 选“Codelf”就会立即打开 Codelf 并搜索出结果

![qq20160906-0](https://cloud.githubusercontent.com/assets/799578/18260825/165b64b8-7424-11e6-9218-a7884ccfe632.png)
# How?

WebStorm 有个 [OnlineSearch](https://plugins.jetbrains.com/plugin/8298?pr=webStorm) 插件，通个它可以添加任意搜索引擎，然后通过快捷键实现一键搜索：
- 1. WebStorm -> Preference -> Plugins -> Browse Repositories... -> 搜索"OnlineSearch"并安装
- 2. WebStorm -> Preference -> Keymap -> 搜索“OnlineSearch” -> 在“Other" 下的 “OnlineSearch”右键 -> 选"Add Keyboard Shortcut" -> 按住“CTRL+S”录入快捷键 -> 点击右下角的“Apply”完成

![qq20160906-1](https://cloud.githubusercontent.com/assets/799578/18261039/f4cae6dc-7425-11e6-8a18-c741fc784c2c.png)
- 3. WebStorm -> Preference -> Other settings -> OnlineSearch -> 三个输入框依次输入：Codelf， `https://unbug.github.io/codelf/#%S` 和 `%S` -> 然后点击”Apply“完成。

![qq20160906-2](https://cloud.githubusercontent.com/assets/799578/18261111/ae14df1c-7426-11e6-96ee-1c3e33c77224.png)

最后你就可以按“Result”里说的2步使用了。

**Comment by unbug** [comment]
你需要自己添加 Codelf 的搜索，按教程里的来

**Comment by unbug** [comment]
我试试看能不能顶上去呢？

**Comment by fengbindev** [comment]
这是我开发的基于IDEA的CODEIF插件 https://gitee.com/quella01/MappingSearch
