### ISSUE TITLE
Request: View "Ungrouped" stars

### ISSUE THREAD

**Issue by someburner** [unbug/codelf#26]
Hi there. Really like this project for it's simplicity and speed. There's a couple things I would find really useful (using the Chrome Add-on):

1. Right now it's hard to see which ones you haven't assigned to a group yet (you have to click the +group button for every one to see them). It would be great to have a way to find all stars in the list that aren't already in at least 1 group. So perhaps underneath the list of groups and above "All", have another group called "No Group" that has all repos that aren't already in at least one group. 

2. Ability to add more tag colors would be nice. Even better, would it be possible to change the tags from colors to hashtags? It would be awesome if you could have a bunch of tags like #tag_1 #tag_2 and assign different colors to them (like GitHub issue Labels).

**Comment by unbug** [comment]
I am glad you like Codelf:
  1. The idea is great, but "No Group" is unnecessary, I think we can add one more checkbox in next to the search box, or apply a search patten such as search with "no-group: repo name".
2. The fist idea of tag was with tag name editable, but everyone says it has no different with the group, why don't I just do it like OS X? So this is the finally version, sample and enough, just like OS X's tag.

So I'll see what I can do with the "No Group" :)

**Comment by unbug** [comment]
@someburner It's done, now when you mouseover a repo, you'll see the group list.

![image](https://cloud.githubusercontent.com/assets/799578/20738627/7f3e48ac-b6ef-11e6-927e-b84941e0fda6.png)

**Comment by someburner** [comment]
Thanks!

For #2.. I agree, but with colors it's very hard to remember what "red" means. But if most people don't like names I'll be okay :+1:

**Comment by unbug** [comment]
@someburner Only 7 colors, that why it's easy to remember, apple's design is great :)

**Comment by someburner** [comment]
Ahh haha that's why. I'm a hardcore linux/android user :)

**Comment by unbug** [comment]
Have no idea what's your mean...
