### ISSUE TITLE
提供alfred版本

### ISSUE THREAD

**Issue by h3l** [unbug/codelf#29]
是否考虑提供alfred的版本

**Comment by unbug** [comment]
推荐用从浏览器打开网址的插件就可以了 ， 如 ｀http://unbug.github.io/codelf/#test｀ 这样就搜 `test` 了

**Comment by elviscai** [comment]
有啊：https://github.com/NauxLiu/Codelf-Workflow

**Comment by unbug** [comment]
Thanks @elviscai
