### ISSUE TITLE
与vscode 不兼容，无法安装

### ISSUE THREAD

**Issue by jjeejj** [unbug/codelf#31]
<img width="1035" alt="codeif" src="https://cloud.githubusercontent.com/assets/15176971/26534313/80367ee8-4455-11e7-8cfb-94d725c3de62.png">

vscode安装codeIf提示不兼容的

vscode版本：1.10.2
codeIf 版本：1.9.0

**Comment by unbug** [comment]
@jjeejj Windows 吗？ 可否升级 VS Code 试试

**Comment by jjeejj** [comment]
@unbug  是最新版的Mac pro (10.12.3 ).  我更新到最新版本试试看
