### ISSUE TITLE
分组设置丢失

### ISSUE THREAD

**Issue by ehlxr** [unbug/codelf#33]
好几次了，分组标记了半天，第二天打开全没了，能不能导出配置啊？

**Comment by unbug** [comment]
你是不是用隐身模式打开呀? 数据会持久化到浏览器的数据库的，理论不会丢失。
当然，你可以远程备份的，点击 `Sync`, 第一次你需要点击 `upload`，（只要输入框是空的就会）得到一个 ID，你可以在任何设别任何浏览器上用这个 ID 进行 `upload`（上传备份），`download` （下载还原）。
你甚至可以分享这个 ID 给任何人作为分享你的分组，或用别人的 ID 获得对方的分组。
注意，分享出去后清空输入框再点击 `upload` 得到一个新的 ID，否则别人可能覆盖你的设置。

![image](https://user-images.githubusercontent.com/799578/28607343-12374d14-720e-11e7-90e1-412e1cd8b440.png)

**Comment by ehlxr** [comment]
@unbug 这个 sync id 是自动生成的啊，我还以为自己输入的了

**Comment by laris** [comment]
分组信息是同步到哪里去了？
如何确保同步呢？

**Comment by unbug** [comment]
@laris 分组默认是不同步的，你需要先upload 后得到一个sync id, 然后自己保存这个id, 下次再用它download.
