### ISSUE TITLE
vscode 插件并没有搜到啊

### ISSUE THREAD

**Issue by yedajiang44** [unbug/codelf#37]
vscode 插件并没有搜到啊

**Comment by unbug** [comment]
是不是写成 “codeif” 了，是 “codelf”. L 不是 i
![image](https://user-images.githubusercontent.com/799578/30816443-961f1d30-a1db-11e7-9dbd-17c93ab8b72d.png)

**Comment by unbug** [comment]
今天突然多了几千人，请问你们是从哪里来的？

**Comment by yedajiang44** [comment]
最近都快火爆了，难道你不知道？？？

**Comment by unbug** [comment]
你在哪看到的，有来源链接吗？

**Comment by yedajiang44** [comment]
我是在头条上看到的。。。蓝后就跑到github上找到了这里

**Comment by unbug** [comment]
原来被上了头条，谢谢啦
