### ISSUE TITLE
中文搜索出问题

### ISSUE THREAD

**Issue by zsfblues** [unbug/codelf#44]
为什么不支持中文搜索了，一直提示找不到
![image](https://user-images.githubusercontent.com/9928627/34592189-45772f2c-f1fd-11e7-97b6-93e8ff65cfeb.png)

**Comment by zsfblues** [comment]
已恢复

**Comment by 1015450578** [comment]
我也遇到中文搜索无法搜索的问题

**Comment by unbug** [comment]
哈，有道翻译的 HTTPS 证书挂了，你们用 http://unbug.github.io/codelf/

**Comment by changheluoriyuan** [comment]
我使用Chrome也无法使用中文搜索，只能搜索应为

**Comment by unbug** [comment]
@changheluoriyuan 参看这个哦 https://github.com/unbug/codelf/issues/58
