### ISSUE TITLE
chrome app 安装后搜索结果无法复制

### ISSUE THREAD

**Issue by dingmuqi** [unbug/codelf#45]
系统:win7
chrome:版本 63.0.3239.132（正式版本） （64 位）
安装后使用效果：
![image](https://user-images.githubusercontent.com/2850652/37442553-f3ca8e46-2841-11e8-84bc-8de81d271753.png)

**Comment by unbug** [comment]
复制需要 Flash 。。。。。。:( 改天更新一下。

**Comment by dingmuqi** [comment]
好的 谢谢。 
chrome://settings/content/flash 管理里面好像无法将chrome app移除禁止列表

**Comment by unbug** [comment]
这么蛋疼。。。。改天再修一下，自己suang'ji

**Comment by unbug** [comment]
我已经换了剪贴板不用flash了
