### ISSUE TITLE
error: not work in idea 2018.1

### ISSUE THREAD

**Issue by MisterChangRay** [unbug/codelf#47]
press down `ctrl + ;`, input some char, those char show in idea editor;

#######################################
IntelliJ IDEA 2018.1 (Ultimate Edition)
Build #IU-181.4203.550, built on March 27, 2018
Licensed to rui.zhang
You have a perpetual fallback license for this version
Subscription is active until December 31, 2099
JRE: 1.8.0_152-release-1136-b20 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 7 6.1

**Comment by unbug** [comment]
不是很理解你的问题，可以自查 [WiKi](https://github.com/unbug/codelf/wiki) 一下
