### ISSUE TITLE
在新版本chrome浏览器下报错

### ISSUE THREAD

**Issue by ihhu** [unbug/codelf#48]
![报错截图](https://user-images.githubusercontent.com/10446605/39975122-4d351400-575f-11e8-8a86-9274a7f9c2ee.png)

**Comment by unbug** [comment]
Chrome 66 木事呀

**Comment by unbug** [comment]
你需要用 HTTPS： https://unbug.github.io/codelf/

**Comment by forsaken628** [comment]
@unbug 那麻烦做个跳转啊，还以为是ff兼容性有问题呢。。。
