### ISSUE TITLE
新版谷歌浏览器 打开网站有bug

### ISSUE THREAD

**Issue by eluotao** [unbug/codelf#51]
我更新了chrome 浏览器 打开本网站 出现bug  输入任何内容 都搜索
Google Chrome 已是最新版本
版本 69.0.3497.81（正式版本） （64 位）

烦请作者 看看.

**Comment by unbug** [comment]
https://github.com/unbug/codelf/issues/45
重了，改天看看

**Comment by acegank** [comment]
直接报了一个事件错误了。。。 用都用不了

**Comment by unbug** [comment]
不要使用 http, 需要HTTPs: https://unbug.github.io/codelf/
