### ISSUE TITLE
【Q&A】为什么中文无法搜索？

### ISSUE THREAD

**Issue by unbug** [unbug/codelf#58]
如果你遇到下图，即中文突然无法搜索了，详细原因解释如下：

**Codelf 需要先到有道翻译API 取中文（事实上你可以搜日文，韩文等）的英文翻译再搜索 GitHub 要变量。我用的是有道翻译API 的免费套餐，目前，一小时超过 1k~2K 请求就会被封一个小时，所以一个小时后再来就好啦！**

![image](https://user-images.githubusercontent.com/799578/50328100-b2ebab80-052c-11e9-96f7-1fb421b6a968.png)

**Comment by never615** [comment]
@丁磊  大佬,来个免费套餐

**Comment by VDerGoW** [comment]
百度翻译的API能用吗？用过不少翻译工具，一直觉得百度翻译的准确度要好过其他的翻译工具。

**Comment by unbug** [comment]
可以用，现在用不上

**Comment by lylyqqy** [comment]
不能直接用吗？需要自己安翻译API 套餐？

**Comment by lylyqqy** [comment]
> 可以用，现在用不上

不能直接用吗？需要自己安翻译API 套餐？

**Comment by baozhadepiqiu** [comment]
能使用缓存解决这个问题么？

**Comment by Ramon403** [comment]
能不能自己配置自己的翻译API的Key呢？

**Comment by ZexiFangkong** [comment]
大佬们, 中文的搜索还是没有解决吗, 现在还是搜不了

**Comment by unbug** [comment]
@ZexiFangkong 你要搜索什么？
![image](https://user-images.githubusercontent.com/799578/212720387-d624a8d8-8348-4f56-bcbf-ecfc375ab7fb.png)
