### ISSUE TITLE
vscode没有对应插件

### ISSUE THREAD

**Issue by utmostP** [unbug/codelf#59]
![image](https://user-images.githubusercontent.com/34041139/50340439-eee73680-0555-11e9-9619-e72dcc944003.png)
![image](https://user-images.githubusercontent.com/34041139/50340459-00304300-0556-11e9-81ea-4f8c496d9ef5.png)

**Comment by unbug** [comment]
有呀 https://marketplace.visualstudio.com/items?itemName=unbug.codelf

**Comment by utmostP** [comment]
谢谢，不知道为什么搜不到😓

**Comment by unbug** [comment]
@utmostP 我试了一下，VS Code 里搜索不能回车，输入会直接提示，回车会返回一堆模糊匹配，感觉很蠢
