### ISSUE TITLE
Codelf for Sublime Text 版本打开网页失败

### ISSUE THREAD

**Issue by Mintcat10** [unbug/codelf#60]
环境Windows10，刚开始网页访问不了，后来把Mdnsearch.py文件的url中的http改成https，才可以成功查询。

**Comment by unbug** [comment]
我强制开启了 HTTPs, 会自动跳转，可能 Window Edge 默认就把 HTTP 给阻拦了。之后更新

**Comment by unbug** [comment]
已经发了新的版本 https://github.com/unbug/codelf/archive/st-0.0.5.zip

**Comment by Mintcat10** [comment]
：）
