### ISSUE TITLE
我需要一个集成，不知道是否可以？

### ISSUE THREAD

**Issue by eluotao** [unbug/codelf#75]
我说的这个需求
一般在培训机构 学生自学 新手项目中 会经常用到。
作为中国人 字段注释都喜欢用中文标示

关于变量这里 我想实现的是在输入框输入以下信息
个人信息类
姓名
年龄
出生日期
城市
地区
乡镇
公司
职位

提交这些中文之后 
你这里能直接后台返回 json格式的信息
姓名 name
年龄 age
出生日期 birthday
城市 city
地区 region
乡镇 random
公司 company
职位 position

好处就是 
我只需要把所有的字段 都用中文写好
直接提交给你
你可以根据我的需要直接生成一整套方案.

如果我对某一个字段的命名不习惯 可以在前台直接可视化选择 那就更好了.

目前来看  能返回json 就不错了.

不知道我这个需求 怎么样?

**Comment by unbug** [comment]
目前不支持接口，不过如果你只需要这样的效果，直接集成有道翻译API，或百度词典API即可

**Comment by Anthony-jhp** [comment]
> 我说的这个需求
> 一般在培训机构学生自学新手项目中会经常用到。
> 作为中国人细分注释都喜欢用中文标示
> 
> 关于变量这里我想实现的是在输入框输入以下信息
> 个人信息类
> 姓名
> 年龄
> 出生日期
> 城市
> 地区
> 乡镇
> 公司
> 职位
> 
> 提交这些中文之后
> 你这里能直接后台返回json格式的信息
> 姓名名称
> 年龄年龄
> 出生日期生日
> 城市城市
> 地区地区
> 乡镇随机
> 公司公司
> 职位
> 
> 好处就是
> 我只需要把所有的分支都用中文写好直接
> 提交给你
> 你可以根据我的需要直接生成一整套方案。
> 
> 如果我对某一个单一的命名不习惯可以在前台直接可视化选择那就更好了。
> 
> 目前来看能返回json就不错了。
> 
> 不知道我这个需求怎么样？

你好，我也是有一样的要求 后来发现是调用<https://searchcode.com/api/>这里的api 或许您也可以调用这里的api 返回的json

**Comment by Anthony-jhp** [comment]
> 我说的这个需求
> 一般在培训机构学生自学新手项目中会经常用到。
> 作为中国人细分注释都喜欢用中文标示
> 
> 关于变量这里我想实现的是在输入框输入以下信息
> 个人信息类
> 姓名
> 年龄
> 出生日期
> 城市
> 地区
> 乡镇
> 公司
> 职位
> 
> 提交这些中文之后
> 你这里能直接后台返回json格式的信息
> 姓名名称
> 年龄年龄
> 出生日期生日
> 城市城市
> 地区地区
> 乡镇随机
> 公司公司
> 职位
> 
> 好处就是
> 我只需要把所有的分支都用中文写好直接
> 提交给你
> 你可以根据我的需要直接生成一整套方案。
> 
> 如果我对某一个单一的命名不习惯可以在前台直接可视化选择那就更好了。
> 
> 目前来看能返回json就不错了。
> 
> 不知道我这个需求怎么样？

你可以调用<https://searchcode.com/api/>
