### ISSUE TITLE
建议添加功能：选择命名方法

### ISSUE THREAD

**Issue by a775691134** [unbug/codelf#76]
建议添加命名方法的选择 以便复制然后直接使用
在网站上提供一般常用的命名方法供用户选择，然后将返回的信息转为相应的命名方法的变量名。

**Comment by unbug** [comment]
你可以详细描述这个功能这么用吗？举个栗子🌰？

**Comment by a775691134** [comment]
抱歉，我没有表达清楚我的用意。
比如在js中，一般变量名使用小驼峰命名法： smallCamel  ts接口、类型和js的类的话使用大驼峰命名规则： BigCamel
php中一般使用`$`开头 `_`连接两个不同的单词，如： $php_variable。
在css中，一般使用中横线将两个单词分开，例如： css-variable

如果在网站中添加了这个功能，就可以一键复制就可以拿过去用了。有的时候可能需要自己去修改命名规则。

**Comment by unbug** [comment]
你试试选语言过滤看看？搜索框的下拉里

**Comment by a775691134** [comment]
我看到啦，抱歉。 之前没有知道这个功能。
