### ISSUE TITLE
It is recommended to increase the options for programming languages when searching. 

### ISSUE THREAD

**Issue by brizer** [unbug/codelf#77]
It is recommended to increase the options for programming languages when searching. 
For example, I am a front-end engineer, I just want to find examples in js files or ts files. This will save a lot of time.
If you can, I can also support this part of the work.

**Comment by unbug** [comment]
![image](https://user-images.githubusercontent.com/799578/59740888-02bcec80-929c-11e9-834d-ce50e185e303.png)

Codelf supports 90+ programming languages. But you can always filter specific languages from the popular language dropdown.

**Comment by brizer** [comment]
Cool！ Thanks. So, where is Typescript?

**Comment by unbug** [comment]
If you search JavaScript, TypeScript will be included. TypeScript is another form of JavaScript, the same as NodeJS.

**Comment by brizer** [comment]
Thanks.
