### ISSUE TITLE
本地怎么安装

### ISSUE THREAD

**Issue by luke0922** [unbug/codelf#8]
本地安装后搜索没有效果

**Comment by unbug** [comment]
我不太明白你的本地安装是什么意思呢？window10的功能吗？Codelf是个网页，在浏览器里打开就能用的呀，推荐用Chrome浏览器

**Comment by unbug** [comment]
我大概明白你的意思了，你是说将你将Codelf的源码在本地运行是吧？你需要家一个HTTP server；或者你成功运行`gulp`后直接访问`http://localhost:3000`就可以了

**Comment by luke0922** [comment]
我在docker 上用 gulp 跑起来了，然而输入关键字后点 “search”没有反应。。。@unbug

**Comment by unbug** [comment]
你要注意有效分支是gh-pages。还有其他问题你用Chrome 的Devtool调试一下，看是什么情况。

**Comment by luke0922** [comment]
终于可以了，你提交的代码有点问题：
codelf/src/lib/libs.381945f7.js 这个文件应该改成名字

codelf/src/lib/libs.js，不然在 index.html 里面引用错了。@unbug

**Comment by unbug** [comment]
过程是自动编译的，会自动改名称，可能编译有点问题没有替换成功。目前编辑我是临时做的，周末会整理一下。
