### ISSUE TITLE
为什么没有开发IDEA的CodeIf插件？

### ISSUE THREAD

**Issue by zhengb0** [unbug/codelf#81]
我想请教一下作者，IDEA这个IDE用的这么多，为什么没有开发这款IDE的codeIf插件呢？
是因为作者时间有限没去开发，还是碰到了什么困难？比如发布到插件库需要凭证？还是其他的，最近有意向开发一下IDEA的这款插件，希望作者可以指点一下。

**Comment by unbug** [comment]
IDEA  已经有很多搜索插件，自己添加一下就可以了，参看：
【教程】给 WebStorm 添加 Codelf 实现一键搜索 : https://github.com/unbug/codelf/issues/24
【教程】5分钟给你喜爱的编辑器开发 CODELF 插件: https://github.com/unbug/codelf/issues/66

**Comment by zhengb0** [comment]
> IDEA 已经有很多搜索插件，自己添加一下就可以了，参看：
> 【教程】给 WebStorm 添加 Codelf 实现一键搜索 : #24
> 【教程】5分钟给你喜爱的编辑器开发 CODELF 插件: #66

感谢作者
