### ISSUE TITLE
unbug.github.io 不能访问

### ISSUE THREAD

**Issue by hereis00** [unbug/codelf#97]
[unbug.github.io](unbug.github.io) 不能访问，是不再支持网站了吗？

**Comment by wangyao** [comment]
https://unbug.github.io/codelf/ 
同上，无法访问

**Comment by cctv180** [comment]
同上，无法访问+1024
还请大佬修一修

**Comment by unbug** [comment]
现在可以访问了吗？可能被墙了？😂

**Comment by cctv180** [comment]
> 现在可以访问了吗？可能被墙了？😂

可以啦非常感谢，每天都要用的呢

**Comment by cctv180** [comment]
您好，我找到原因了DNS解析问题，DNS里面有指向127.0.0.1   ::1 本机地址，手工在路由添加unbug.github.io指向185.199.110.153刷新DNS缓存后解决。

https://ping.chinaz.com/unbug.github.io
![Snipaste_2020-09-07_11-18-05](https://user-images.githubusercontent.com/29967144/92345624-a6dabf80-f0fc-11ea-9be4-b5e47427b9af.png)
![Snipaste_2020-09-07_11-18-25](https://user-images.githubusercontent.com/29967144/92345639-b6f29f00-f0fc-11ea-87e1-9e6427db9985.png)

**Comment by UmbraCi** [comment]
> 您好，我找到原因了DNS解析问题，DNS里面有指向127.0.0.1 ::1 本机地址，手工在路由添加unbug.github.io指向185.199.110.153刷新DNS缓存后解决。
> 
> https://ping.chinaz.com/unbug.github.io
> ![Snipaste_2020-09-07_11-18-05](https://user-images.githubusercontent.com/29967144/92345624-a6dabf80-f0fc-11ea-9be4-b5e47427b9af.png)
> ![Snipaste_2020-09-07_11-18-25](https://user-images.githubusercontent.com/29967144/92345639-b6f29f00-f0fc-11ea-87e1-9e6427db9985.png)

ping命令不是走的icmp第三层网络协议“网络层”吗，你是在哪儿添加的路由，host文件添加ping照样没绕开

**Comment by unbug** [comment]
我用的直接是 github pages，没有自己设置 DNS，可能是被墙了
